Shop.WebApplication/Shop.Web/Models/Shared/ConfirmViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shop.Web.Models.Shared
{
    public class ConfirmViewModel
    {
        public string Message { get; set; }

        public string Url { get; set; }

        public string Value { get; set; }
    }
}

Shop.WebApplication/Shop.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Shared.Entities;
using Shop.Shared.Entities.Enums;
using Helper = Shop.Shared.Helpers.RoleHelper;
using Shop.Web.Attributes;

namespace Shop.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        public ActionResult ShowAdminPanel()
        {
            if (!Helper.CheckPermissions((User)Session["User"], RoleType.Administrator, RoleType.Moderator))
            {                                                       //проверяет принадлежность к этим ролям
                ViewBag.Warning = "Ахтунг! Недостаточно прав для доступа к этой панели!";
                return View("~/Views/Shared/UserError.cshtml");
            }
            return View();
        }
    }
}

Shop.WebApplication/Shop.Web/Controllers/Image/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Web.Models;
using Shop.Business.Services;
using Shop.Business.Services.Interfaces;

namespace Shop.Web.Controllers
{
    public class ImageController : Controller
    {
        private IImageService _imageService;

        public ImageController(IImageService imageService)
        {
            this._imageService = imageService;
        }

        public ActionResult ShowTestImages()
        {
            return View(
                new ImageViewModel
                {
                    Images = _imageService.GetAllByUserId(1)
                });
        }
    }
}

Shop.WebApplication/Shop.Web/Views/Shared/Confirm.cshtml
@using Shop.Web.Models.Shared;
@model ConfirmViewModel
@{
    ViewBag.Title = "ConfirmationMenu";
}

<h2>Подтвердите ваше действие</h2>
<p>@Model.Message</p>
<form action="@Model.Url">
    <input type="hidden" value="@Model.Value" name="id" />
    <button class="btn waves-effect waves-light" type="submit">Подтвердить</button>
</form>
<br />
<input style="width:75px" class="btn waves-effect waves-light" type="button" onclick="history.back();" value="Назад" />

Shop.WebApplication/Shop.Web/Views/Shared/Notification.cshtml
@{
    ViewBag.Title = "Уведомление";
}

<h2>@ViewBag.Message</h2>

<form action="~/Home/Index">
    <button class="btn waves-effect waves-light">Главное меню</button>
</form>

Shop.WebApplication/Shop.Web/Views/Shared/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

Shop.WebApplication/Shop.Web/Views/Shared/UserError.cshtml
@{
    ViewBag.Title = "Ашыбка!";
}

<h2>У-у-упс! Что-то пошло не так...</h2>
<h3>@ViewBag.Warning</h3>

Shop.WebApplication/Shop.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using Shop.Shared.Entities.Enums;
@using Shop.Shared.Entities.Authorize;

@{
    var user = User as UserPrinciple;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/ajax")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AglyExpress", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Люди", "UserSearch", "User")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Картинки", "ShowTestImages", "Image")</li>
                    @if (user != null && user.IsInRole(RoleType.Administrator.ToString()))
                    {
                        <li>@Html.ActionLink("Admin Panel :D", "ShowAdminPanel", "Admin", routeValues: null, htmlAttributes: new { id = "adminPanelLink" })</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – курсовая на ASP.NET</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>